<mainNavigation>:
    screenManager : screenManager
    container:container
    ScreenManager:
        id: screenManager
        Screen:
            name: 'subscriptions'
            Carousel:
                id: container

            MDFloatingActionButton:
                pos_hint: {'center_x': .5, 'center_y': .1}
                icon: "message-bulleted"
                theme_text_color: "Custom"
                md_bg_color: app.theme_cls.primary_color
                #on_release:






