<mainNavigation>:
    screenManager : screenManager
    container:container
    ScreenManager:
        id: screenManager
        Screen:
            name: 'subscriptions'
            Carousel:
                id: container
            MDBottomAppBar:
                MDToolbar:
                    title: "Entity"
                    icon: "message-bulleted"
                    type: "bottom"
                    left_action_items: [["graph", lambda x: x]]
                    mode: "end"




